[project]
name = "huami_token"
version = "0.8.0"
description = "This script retrieves the Bluetooth access token for the watch or band from Huami servers. Additionally, it downloads the AGPS data packs, cep_alm_pak.zip and cep_7days.zip."
readme = "README.md"
requires-python = ">=3.8"
authors = [
  { name = "Kirill Snezhko", email = "kirill.snezhko@pm.me" },
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

dependencies = [
  "loguru>=0.7.3",
  "pycryptodome>=3.23.0",
  "requests>=2.31.0,<3",
]

[project.optional-dependencies]
dev = [
  "pytest>=8,<9",
  "pytest-flake8>=1.1.3",
  "pytest-pylint>=0.20.0",
  "types-requests>=2.31.0.20231231",
  "ruff>=0.5,<1",
  "mypy>=1.10,<2",
]

[project.urls]
"Homepage" = "https://codeberg.org/argrento/huami-token"
"Bug Tracker" = "https://codeberg.org/argrento/huami-token/issues"

[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["huami_token"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.mypy]
python_version = "3.11"
warn_unused_ignores = true
warn_redundant_casts = true
